/wof/code/cmd_export_matching_sheet.sh      locality
/wof/code/cmd_export_matching_sheet.sh      country
/wof/code/cmd_export_matching_sheet.sh      county
/wof/code/cmd_export_matching_sheet.sh      region
/wof/code/cmd_export_matching_sheet.sh      dependency
/wof/code/cmd_export_matching_sheet.sh      disputed
/wof/code/cmd_export_matching_sheet.sh      macroregion
/wof/code/cmd_export_matching_sheet.sh      macrocounty
/wof/code/cmd_export_matching_sheet.sh      localadmin
/wof/code/cmd_export_matching_sheet.sh      campus
/wof/code/cmd_export_matching_sheet.sh      borough
/wof/code/cmd_export_matching_sheet.sh      macrohood
/wof/code/cmd_export_matching_sheet.sh      neighbourhood
/wof/code/cmd_export_matching_sheet.sh      microhood
/wof/code/cmd_export_matching_sheet.sh      planet
/wof/code/cmd_export_matching_sheet.sh      continent
/wof/code/cmd_export_matching_sheet.sh      ocean
/wof/code/cmd_export_matching_sheet.sh      timezone
/wof/code/cmd_export_matching_sheet.sh      marinearea